#!/bin/sh

[ ! -e ~/logs ] && mkdir ~/logs

`cd ~/logs && /usr/sbin/logrotate -f -s ~/etc/logrotate.state ~/etc/steeplechase-long.rotate.conf`
~/bin/steeplechase-long > ~/logs/steeplechase-long.log 2>&1
